services:
  home:
    build: ./Home
    ports:
      - "3000:3000"
  TicTacToe:
    build: ./TicTacToe
    ports:
      - "3100:3100"
  Battleship:
    build: ./Battleship
    ports:
      - "3200:3200"
